/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXWARPCallee,
  IXWARPCalleeInterface,
} from "../../../contracts/interfaces/IXWARPCallee";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amount1",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "XWARPCall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IXWARPCallee__factory {
  static readonly abi = _abi;
  static createInterface(): IXWARPCalleeInterface {
    return new Interface(_abi) as IXWARPCalleeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IXWARPCallee {
    return new Contract(address, _abi, runner) as unknown as IXWARPCallee;
  }
}
